version: "3.9"

services:
  app:
    build: .
    container_name: vidly-backend
    command: npm run start
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports: 
      - "8080:8080"
    env_file:
      - .env
    
